name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest-cov
          pip install -r requirements.txt
      - name: Lint with Black
        run: |
          black --check yaml_resume
      - name: Tests with Pytest
        run: |
          python -m pytest --cov=yaml_resume --cov-report xml:test-results/coverage.xml --junitxml=test-results/junit.xml
      - name: Fix code coverage paths
        if: matrix.python-version == 3.12
        run: |
          sed -i 's#/home/runner/work/yaml-resume/yaml-resume/#/github/workspace/#g' test-results/coverage.xml
